// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_vector_search from "./routes/api/vector-search.ts";
import * as $index from "./routes/index.tsx";
import * as $SearchDialog from "./islands/SearchDialog.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/vector-search.ts": $api_vector_search,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/SearchDialog.tsx": $SearchDialog,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
